home:
    path:     /
    controller: App\Controller\Home
    allowed_methods: ['get']

insert-task-form:
    path: insert-task-form
    controller: App\Controller\InsertForm    
    allowed_methods: ['get']

insert-task:
    path: insert-task
    controller: App\Controller\Insert    
    allowed_methods: ['get', 'post']

delete-task:
    path: delete-task
    controller: App\Controller\Delete    
    allowed_methods: ['get']