home:
    path:     /
    controller: App\Controller\Home
    allowed_methods: ['get']

insert-user:
    path: insert-user
    controller: App\Controller\Insert    
    allowed_methods: ['post']

delete-user:
    path: delete-user-user
    controller: App\Controller\Delete    
    allowed_methods: ['get']