home:
    path:     "/"
    allowed_methods: ['get']

some-page:
    path: "some-page"
    allowed_methods: ['get']

some-{variable}-page:
    path: "some/{variable}/page"
    allowed_methods: ['get']